### ISSUE TITLE
PHP Library

### ISSUE THREAD

**Issue by tatumio** [tatumio/roadmap#10]

**Comment by nowackipawel** [comment]
Hi @tatumio Will your team prepare library or should we develop our solution further? ;-)
I am just curious  - in fact my solution is working pretty well right now, but I would like to know if there will be something official that we could migrate in the future.

**Comment by samuelsramko** [comment]
Hey, we will improvements in the library in the future, but we have no specific timeline for that. :-)

**Comment by nowackipawel** [comment]
Ok, gr8. Thx.
