### ISSUE TITLE
Future trading method

### ISSUE THREAD

**Issue by DavoodRm** [tatumio/roadmap#30]

**Comment by tatumio** [comment]
Hey, can you please provide more description of expected functionality? Thank you 👍

**Comment by DavoodRm** [comment]
A futures trade is an agreement based on the buy/sale of a specified asset at a specified time in the future at a specified price.

Futures trade are bilateral and we can sell the assets with certain specifications without having any assets, and in the future (after a few hour/day/month) we will deliver it at the price we have agreed on now and receive the money.
Futures can also be traded in crypto currencies.

**Comment by DavoodRm** [comment]
In this way of trading. In addition to the price and currency pairs for the trade, the maker set blocks the percentage and specifies the time of the trade.
takers can now trade, but the full trade will not be done and will only be blocked in the accounts, so the two parties do not need to have the total amount, having a limited amount of money is enough and it will be blocked in their account and must be at the appointed time. Have the full amount to trade

    Otherwise, the trade will be done as much as the balance of the parties

**Comment by tatumio** [comment]
Idealy if you could enter examples of the account balances, trade definitions and resulting transactions when trade is matched and closed. Example on the real life data is always usefull

**Comment by DavoodRm** [comment]
User can buy full or partial amount of the offer (if user has enough blocked percentage of fiat)
with the offered price but not less than 100 Euro or equal. Then user can send  buy offer and
deal will seal and will do on the deadline. When trader send offer, system will block the percentage, will
deduct commission from maker and taker and will wait for the deadline to arrange the deal. At
the same time system should deduct Futures sealed deal amount from original offer and just show the
remaining in the list of the offers. If whole amount accepted by taker then offer will remove from
the list. Offer will transfer to the open order list of the maker and taker with ability of cancelation
until 95% time interval passed only (a percentage of the time passed should show). If cancelled,
then penalty will pay to the other side of the deal from the user who cancelled the deal. At the
time of the deal fiat and crypto from the maker and taker will deduct and will add to the
opponent valet. At the same time blocked amount from maker and taker for this deal will release.
If maker and taker do not have enough fiat or crypto, then maximum available percentage
possible of deal should done and each side which do not have enough fiat or crypto should pay
penalty to other side.

**Comment by DavoodRm** [comment]
Example
maker creates 1btc for sale in btc / eur deal with 22% block and 72 hours delay and therefore should only have 0.22% in your wallet
Now the taker accepts this deal and only needs to have 22% of the price of 1 btc to seal the deal.
Now, 72 hours after tltrade to be done, both parties must have the full amount in their wallet so that trade can be done, and if they do not have it, trade will be equal to the balance and the penalty will be the party who does not have the full balance.

**Comment by Hathoriel** [comment]
Hi @DavoodRm  _therefore should only have 0.22% in your wallet_ By this you mean 22%

**Comment by DavoodRm** [comment]
> Example
> maker creates 1btc for sale in btc / eur deal with 22% block and 72 hours delay and therefore should only have 0.22% in your wallet
> Now the taker accepts this deal and only needs to have 22% of the price of 1 btc to seal the deal.
> Now, 72 hours after tltrade to be done, both parties must have the full amount in their wallet so that trade can be done, and if they do not have it, trade will be equal to the balance and the penalty will be the party who does not have the full balance.



> Hi @DavoodRm _therefore should only have 0.22% in your wallet_ By this you mean 22%

yes 22% = 0.22

**Comment by Hathoriel** [comment]
> Now, 72 hours after tltrade to be done, both parties must have the full amount in their wallet so that trade can be done, and if they do not have it, trade will be equal to the balance and the penalty will be the party who does not have the full balance.

What if both parties don't have a full balance?

**Comment by DavoodRm** [comment]
They pay each other fines based on the remaining amount

**Comment by DavoodRm** [comment]
Penalty amount = (Percentage of none deal amount because of shortage from user) X (Maximum
Penalty percentage of futures deal based on blocked amount and time interval) X (total blocked
value)

**Comment by Hathoriel** [comment]
> When trader send offer, system will block the percentage, will
deduct commission from maker and taker and will wait for the deadline to arrange the deal. 

What do you mean deduct commission? Could you please provide an example of that?

**Comment by Hathoriel** [comment]
> > When trader send offer, system will block the percentage, will
> > deduct commission from maker and taker and will wait for the deadline to arrange the deal.
> 
> What do you mean deduct commission? Could you please provide an example of that?



> Penalty amount = (Percentage of none deal amount because of shortage from user) X (Maximum
> Penalty percentage of futures deal based on blocked amount and time interval) X (total blocked
> value)

Could you please provide an example with real data? With setup and so on?

**Comment by DavoodRm** [comment]
This means that at the time of registration of the transaction, the system commission will be paid first, even if both parties to the transaction do not have money at the time of the transaction.

**Comment by Hathoriel** [comment]
What about the side which creates future trade (maker), that side should have blocked only some percentage of their amount or full amount? I understand that side that agrees on the future trade (taker) should only have part of the amount.

**Comment by Hathoriel** [comment]
> This means that at the time of registration of the transaction, the system commission will be paid first, even if both parties to the transaction do not have money at the time of the transaction.

What do you mean by system commission? Could you please add some example with real data?

**Comment by DavoodRm** [comment]
example 1:
Blocked percentage: 12%
Time interval: 12 hrs
Maximum penalty percentage from blocked amount:15%

For a deal of 1000 Euro, for an interval of 12 hours and with a blocked percentage of 12 % by
maker, if maker cannot full fill the amount and just be able to fulfill 30% of the deal then amount
of maker penalty to taker will calculate (based on fiat or crypto) as follow:
Penalty amount = (70%) X (15%) X (1000 x 12%) = 12.60 Euro

**Comment by DavoodRm** [comment]
Both parties future trade only need to be sealed at the time of the teacher

**Comment by Hathoriel** [comment]
> example 1:
> Blocked percentage: 12%
> Time interval: 12 hrs
> Maximum penalty percentage from blocked amount:15%
> 
> For a deal of 1000 Euro, for an interval of 12 hours and with a blocked percentage of 12 % by
> maker, if maker cannot full fill the amount and just be able to fulfill 30% of the deal then amount
> of maker penalty to taker will calculate (based on fiat or crypto) as follow:
> Penalty amount = (70%) X (15%) X (1000 x 12%) = 12.60 Euro

Ok, now I get it. And to be clear, you created this formula or the formula is just a start in the world of futures how to handle penalties? Could you add some resource if this is a standard?

**Comment by Hathoriel** [comment]
> Both parties future trade only need to be sealed at the time of the teacher

What do you mean by the time of the teacher?

**Comment by DavoodRm** [comment]
example 2:
Blocked percentage: 22%
Time interval: 60 hrs
Maximum penalty percentage from blocked amount:80%

For a deal of 1000 Euro, for an interval of 60 hours and with a blocked percentage of 22 % by
maker, if maker cannot full fill the amount and just be able to fulfill 30% of the deal then amount
of maker penalty to taker will calculate (based on fiat or crypto) as follow:
Penalty amount = (70%) X (80%) X (1000 x 22%) = 123.20 Euro

**Comment by DavoodRm** [comment]
> Ok, now I get it. And to be clear, you created this formula or the formula is just a standard in the world of futures how to handle penalties? Could you add some resource if this is a standard?

Percentage of fines does not have a standard formula and is such that the percentage of fines can be deducted from the blocked amount

**Comment by DavoodRm** [comment]
> What do you mean by the time of the teacher?
I wrote it wrong....
This means that. The two parties futures trade should only have a blocked percentage at the time of the trade register.

**Comment by Hathoriel** [comment]
Great! Thanks for your answers. Maybe more will come in future.

**Comment by Hathoriel** [comment]
Hi @DavoodRm, could one sell have assigned multiple buys? If yes, how many buys could be assigned with one sell? Thank you.

**Comment by DavoodRm** [comment]
> Hi @DavoodRm, could one sell have assigned multiple buys? If yes, how many buys could be assigned with one sell? Thank you.

Yes, it is possible in future trade.
And will be similar to a limit spot

**Comment by Hathoriel** [comment]
> > Hi @DavoodRm, could one sell have assigned multiple buys? If yes, how many buys could be assigned with one sell? Thank you.
> 
> Yes, it is possible in future trade.
> And will be similar to a limit spot

What is a limit spot?

**Comment by DavoodRm** [comment]
> What is a limit spot?
> I think one-to-many will a little more complicated 
operations behind that, I will go for one-to-one.
The method you are currently using to trade in tatum services

**Comment by DavoodRm** [comment]
> > What is a limit spot?
> > I think one-to-many will a little more complicated
> 
> operations behind that, I will go for one-to-one.
> The method you are currently using to trade in tatum services
>
A sale offer is created for the trade and buyers can buy as much as they want from that buy offer

**Comment by Hathoriel** [comment]
> > > What is a limit spot?
> > > I think one-to-many will a little more complicated
> > 
> > 
> > operations behind that, I will go for one-to-one.
> > The method you are currently using to trade in tatum services
> 
> A sale offer is created for the trade and buyers can buy as much as they want from that buy offer
> 
> It is not a good idea if a sell offer is made and only one buyer can buy all of it

I know, but this is more complicated. And which one-to-one it should be achieved also.

**Comment by DavoodRm** [comment]
Example 3
trade Btc/usdt

Maker an offer for the next 12 hours: 1 btc at a price of 60000usdt and a blocking percentage of 22% 
=> 0.22 btc blocking on account
taker Accept the offer and  blocking 13200usdt on account
60000usdt × 22% = 13200usdt
Percentage of trade penalty 45% of the blocked amount
At the time of the trade, maker  and taket have the following conditions:
maker asset to trade 0.65 btc (35% deficit)
taker asset to trade 49200 usdt (18% deficit)
mamer penalty =
0.35 × 0.22 × (0.45 × 1 btc)= 0.03465 btc
taker penalty =
0.18 × 0.22 × (0.45 × 60000 usdt) = 1069.2 usdt

System Commission from Maker
1 btc × 1% = 0.01 btc
System commission from Taker
60000 usdt × 1% = 600 usdt
maker assets after deducting fines and commissions
0.65 - 0.03465-0.01 = 0.60535 btc
Taker assets after deducting commissions and fines
49200-1069.2 - 600 = 47530.8 usdt

The amount received by the maker after the trade
(0.60535 × 60000)+1069.2= 37390.2 usdt

The amount received by the taker after the trade

0.60535 + 0.03465= 0.64 btc

**Comment by DavoodRm** [comment]
> > > > What is a limit spot?
> > > > I think one-to-many will a little more complicated
> > > 
> > > 
> > > operations behind that, I will go for one-to-one.
> > > The method you are currently using to trade in tatum services
> > 
> > 
> > A sale offer is created for the trade and buyers can buy as much as they want from that buy offer
> > It is not a good idea if a sell offer is made and only one buyer can buy all of it
> 
> I know, but this is more complicated. And with one-to-one it should be achieved also. Maybe in future, I will add this feature.
>
Example 3
trade Btc/usdt

Maker an offer for the next 12 hours: 1 btc at a price of 60000usdt and a blocking percentage of 22% 
=> 0.22 btc blocking on account
taker Accept the offer and  blocking 13200usdt on account
60000usdt × 22% = 13200usdt
Percentage of trade penalty 45% of the blocked amount
At the time of the trade, maker  and taket have the following conditions:
maker asset to trade 0.65 btc (35% deficit)
taker asset to trade 49200 usdt (18% deficit)
mamer penalty =
0.35 × 0.22 × (0.45 × 1 btc)= 0.03465 btc
taker penalty =
0.18 × 0.22 × (0.45 × 60000 usdt) = 1069.2 usdt

System Commission from Maker
1 btc × 1% = 0.01 btc
System commission from Taker
60000 usdt × 1% = 600 usdt
maker assets after deducting fines and commissions
0.65 - 0.03465-0.01 = 0.60535 btc
Taker assets after deducting commissions and fines
49200-1069.2 - 600 = 47530.8 usdt

The amount received by the maker after the trade
(0.60535 × 60000)+1069.2= 37390.2 usdt

The amount received by the taker after the trade

0.60535 + 0.03465= 0.64 btc

**Comment by Hathoriel** [comment]
Hi @DavoodRm!
We are finishing heavy development of the futures now, but we will release it soon!
Stay tuned, please!

**Comment by Hathoriel** [comment]
Hi, just for example, creating future sell (buy) will have following format:

```
{
    "type": "FUTURE_SELL", // or FUTURE_BUY
    "price": "3",
    "amount": "10",
    "pair": "ETH/BTC",
    "currency1AccountId": "60ab440d58019206c876b4f6",
    "currency2AccountId": "609d0696bf835c241ac2920f",
    "attr": {
        "sealDate": 1621595470000,
        "percentBlock": 10,
        "percentPenalty": 30
    }
}
```

**Comment by Hathoriel** [comment]
Yes, you can also add fee and feeAccountId. I just forget to add it to the example.
